/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhooksMittwaldRouteImport } from './routes/api/webhooks.mittwald'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMittwaldRoute = ApiWebhooksMittwaldRouteImport.update({
  id: '/api/webhooks/mittwald',
  path: '/api/webhooks/mittwald',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/webhooks/mittwald': typeof ApiWebhooksMittwaldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/webhooks/mittwald': typeof ApiWebhooksMittwaldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/webhooks/mittwald': typeof ApiWebhooksMittwaldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/webhooks/mittwald'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/webhooks/mittwald'
  id: '__root__' | '/' | '/api/webhooks/mittwald'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWebhooksMittwaldRoute: typeof ApiWebhooksMittwaldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mittwald': {
      id: '/api/webhooks/mittwald'
      path: '/api/webhooks/mittwald'
      fullPath: '/api/webhooks/mittwald'
      preLoaderRoute: typeof ApiWebhooksMittwaldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWebhooksMittwaldRoute: ApiWebhooksMittwaldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
